#! /usr/bin/env bash
set -euo pipefail

script_dir=$(dirname $0)

#poetry -C "${script_dir}/python" env use 3.12 &>/dev/null
#py=$(poetry -C "${script_dir}/python" run which python)
#"${py}" "${script_dir}/python/prstack/prstack.py" $@

/Users/seangatewood/Library/Caches/pypoetry/virtualenvs/prstack-YNPLmpjP-py3.12/bin/python "${script_dir}/python/prstack/prstack.py" $@